//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJI_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depatment
    {
        public int Dept_Id { get; set; }
        public string Dept_Name { get; set; }
    }
}
